name: merge check

on:
  pull_request:
    branches:
      - master

jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set npm registry
        uses: actions/setup-node@v1
        with:
          registry-url: http://nexus.saas.hand-china.com/content/groups/hone-npm-group/
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Doc Build
      - run: yarn
      - run: yarn run docs:build

